DROP TABLE PERSON;

CREATE TABLE IF NOT EXISTS PERSON(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    IS_REGISTERED BOOLEAN,
    IS_USA_CITIZEN BOOLEAN
);

INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('John Smith', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Jane Underwood', TRUE, FALSE );
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('James Perkins', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Mary Calderon', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Noah Graves', FALSE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Jake Chavez', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Oliver Aguilar', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Emma Mccann', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Margaret Knight', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Amelia Curry', FALSE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Jack Vaughn', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Liam Lewis', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Olivia Reyes', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Samantha Poole', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Patricia Jordan', FALSE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Robert Sherman', TRUE, FALSE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Mason Burton', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Harry Christensen', FALSE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Jennifer Mills', TRUE, TRUE);
INSERT INTO PERSON(NAME, IS_REGISTERED, IS_USA_CITIZEN) VALUES ('Sophia Graham', FALSE, FALSE);



