###
GET http://localhost:8081/countries
Accept: application/json

###
GET http://localhost:8081/persons

###
GET http://localhost:8081/persons/4

###
PATCH http://localhost:8081/persons/4
Content-Type: application/json

{
  "name": "Sophia Jones",
  "country": "AU",
  "isRegistered": "true"
}

###
DELETE http://localhost:8081/persons/4

###
POST http://localhost:8081/persons
Content-Type: application/json

{
  "name": "John Smith"
}

###
GET http://localhost:8081/persons/4
If-None-Match: "0f363c84b4b7f5ed79e9a59f4c74afa50"

### not supported by ShallowEtagHeaderFilter
GET http://localhost:8081/persons/4
If-Match: "03a6c9f0aa136944e8cb98ade579082dc"


